WACKEN_2026_SOURCE_URLS = [
    "https://www.wacken.com/en/news-details/party-on-the-first-35-bands-for-woa-2026/",
    "https://s.wacken.com/en/news-details/55-additional-bands-for-wacken-open-air-2026/",
    "https://www.wacken.com/en/news-details/49-new-bands-for-woa-2026/",
    "https://www.wacken.com/en/news-details/party-on-with-sabbaton-at-woa-2026/",
    "https://www.wacken.com/en/news-details/more-bands-for-the-holy-ground/",
    "https://www.wacken.com/en/line-up/bands/#/bandfilter",
    "https://www.festivalsunited.com/festivals/wacken-open-air",
]

WACKEN_2026_BANDS = [
    "5th Avenue",
    "5th Avenue Hamburg",
    "9mm Headshot",
    "Ad Infinitum",
    "Airbourne",
    "Alcest",
    "Alestorm",
    "Alfahanne",
    "Alien Ant Farm",
    "Alien Rockin Explosion",
    "Allt",
    "Anaal Nathrakh",
    "Angelus Apatrida",
    "Animals As Leaders",
    "Any Given Day",
    "Arch Enemy",
    "Arroganz",
    "Asrock",
    "Ballroom DJ Team",
    "Battlecreek",
    "Bear McCreary",
    "Blaas Of Glory",
    "Black Label Society",
    "Black Tish",
    "Bleed From Within",
    "Blood Command",
    "Blood Fire Death",
    "Blood Red Throne",
    "Broken By The Scream",
    "Brunhilde",
    "Castle Rat",
    "Chaosbay",
    "Corrosion Of Conformity",
    "Cowgirls From Hell",
    "Craft",
    "Crematory",
    "Crimson Glory",
    "Cruachan",
    "Crypt Sermon",
    "Cursed Abyss",
    "Danko Jones",
    "Deafheaven",
    "Def Leppard",
    "Diabolisches Werk",
    "Dirty Shirt",
    "Divlje Jagode",
    "Dritte Wahl",
    "Dubioza Kolektiv",
    "E.N.D.",
    "Einherjer",
    "Elchivo",
    "Electric Bassboy",
    "Eläkeläiset",
    "Emperor",
    "Employed To Serve",
    "Europe",
    "Evil Jared",
    "Expellow",
    "Faun",
    "Finsterforst",
    "Firespawn",
    "Fit For An Autopsy",
    "Focus",
    "Force",
    "Future Palace",
    "Given By The Flames",
    "Goodnight Greatness",
    "Grand Magus",
    "Guilt Trip",
    "Gutalax",
    "H-Blockx",
    "Hackneyed",
    "Hardline",
    "Hatebreed",
    "Heartless Human Harvest",
    "Heavysaurus",
    "Hämatom",
    "I See Red",
    "In Flames",
    "Insanity Alert",
    "Judas Priest",
    "Kadavar",
    "Katerfahrt",
    "Kärbholz",
    "Kim Dracula",
    "Kittie",
    "Krogi",
    "Kupfergold",
    "Lacuna Coil",
    "Lagwagon",
    "Lamb Of God",
    "Life Of Agony",
    "Lovebites",
    "Luna Kills",
    "Mambo Kurt",
    "Manntra",
    "Mantar",
    "Maschine",
    "Maschine's Late Night Show",
    "Metaklapa",
    "Midhaven",
    "Minotaurus",
    "Misery Index",
    "Misþyrming",
    "Mr. Hurley Und Die Pulveraffen",
    "Municipal Waste",
    "Nevermore",
    "Nita Strauss",
    "Novelization",
    "Of Mice & Men",
    "Orbit Culture",
    "Our Promise",
    "P.O.D.",
    "Paleface Swiss",
    "Paradise Lost",
    "Phantom",
    "Pig Destroyer",
    "Poison The Preacher",
    "Powerwolf",
    "Ricky Warwick",
    "Rose Tattoo",
    "Running Wild",
    "Sabaton",
    "Sacred Steel",
    "Sagenbringer",
    "Savatage",
    "Saviourself",
    "Saxon",
    "Sepultura",
    "Sinamort",
    "Skyline",
    "Skylineband",
    "Skynd",
    "Speak In Whispers",
    "Spectral Wound",
    "Stonem",
    "Storm Seeker",
    "Subway To Sally",
    "Temple Of The Absurd",
    "Ten56",
    "Ten56.",
    "The Butcher Sisters",
    "The Gathering",
    "The Hardkiss",
    "The Haunted",
    "The Limit",
    "The Other",
    "The Troops Of Doom",
    "Therapy?",
    "Thomas Nicholas Band",
    "Thrown",
    "Thundermother",
    "Thy Art Is Murder",
    "Triptykon",
    "Trold",
    "Troops Of Doom",
    "Turbonegro",
    "Tuxedoo",
    "Uli Jon Roth",
    "Unzucht",
    "Vanir",
    "Velvet Rush",
    "Vended",
    "Visions Of Atlantis",
    "Vogelfrey",
    "Vreid",
    "Wacken Firefighters",
    "Wytch Hazel",
    "Wüstenberg",
    "Year Of The Goat",
    "Yngwie Malmsteen",
    "Zeltinger Band",
]
